app:
  build: .
  ports:
  - "8000:80"
  links:
  - "db:db"

db:
  build: ./database
  container_name: db
  volumes:
  - db_data:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: senayandb
