version: '3'

services:
  web:
    build: .
    ports:
    - "8080:80"
    links:
    - "db:db"

  db:
    image: mysql:5.6
    container_name: db
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senayandb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
     - 8181:80

volumes:
  db_data:
